### ISSUE TITLE
element_type_checker() in IterableValidator fails when iterable is empty

### ISSUE THREAD

**Issue by Aparna-BS** [uzumaxy/pyvalid#44]
```
@accepts(list, IterableValidator(empty_allowed=True, elements_type=str)
def example([]):
      pass
```
Iterable Validator fails in the above shown scenario. If we are allowing empty list the user may either provide empty or non-empty list, and the type check should not throw exception when the list is empty.

**Comment by Aparna-BS** [comment]
The fix to this issue is submitted in Pull Request #45.

**Comment by uzumaxy** [comment]
Hello @Aparna-BS ,
Thank you for this fix! I already merged it and deployed a new release, which contains the fix and few other changes as well: https://github.com/uzumaxy/pyvalid/releases/tag/1.0.4
