### ISSUE TITLE
Py3.5: Problem with accepts decorator

### ISSUE THREAD

**Issue by uzumaxy** [uzumaxy/pyvalid#6]
There are few cases when accepts decorator isn't work as expected. Unit tests fails in lines [122 - 123](https://github.com/uzumaxy/pyvalid/blob/master/tests/test_accepts.py#L122), [130 - 131](https://github.com/uzumaxy/pyvalid/blob/master/tests/test_accepts.py#L130), [135 - 136](https://github.com/uzumaxy/pyvalid/blob/master/tests/test_accepts.py#L135) of the `test_accepts.py` file.
Problem is only reproducible for Python version 3.5

**Comment by jeking3** [comment]
I see this in 3.5 CI builds:

https://travis-ci.org/jeking3/pyvalid/builds/547758048
