### ISSUE TITLE
Pip unable to install pyvalid==0.9.1 or pyvalid==0.9.2

### ISSUE THREAD

**Issue by vsevolod-fedorov** [uzumaxy/pyvalid#9]
`seva@spin:~$ /tmp/venv/bin/pip install pyvalid==0.9.2
Collecting pyvalid==0.9.2
  Downloading https://files.pythonhosted.org/packages/f9/37/5a6aafd4cf2d6db43cbf6f79f211d69b48107e2045cdeca906f2eacac5a6/pyvalid-0.9.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-FtnEbh/pyvalid/setup.py", line 81, in <module>
        main()
      File "/tmp/pip-install-FtnEbh/pyvalid/setup.py", line 12, in main
        with open('requirements.txt') as fd:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-FtnEbh/pyvalid/
seva@spin:~$ /tmp/venv/bin/pip install pyvalid==0.9.1
Collecting pyvalid==0.9.1
  Downloading https://files.pythonhosted.org/packages/04/e8/ee039c1b990b6ca2c8af439e05e1bba681eeaf360a1a14e3565fd4914f46/pyvalid-0.9.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-tAmnTm/pyvalid/setup.py", line 81, in <module>
        main()
      File "/tmp/pip-install-tAmnTm/pyvalid/setup.py", line 12, in main
        with open('requirements.txt') as fd:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-tAmnTm/pyvalid/
`

**Comment by vsevolod-fedorov** [comment]
Looks like this is broken by [Moved requirements to separated file](https://github.com/uzumaxy/pyvalid/commit/5ea578c9a12141bc8181ab85d9d8e43cf9d71307#diff-2eeaed663bd0d25b7e608891384b7298)

**Comment by jeking3** [comment]
I have a fix for this, I'll submit a PR shortly.
